Ping boilerplate
giantswarm/heartbeatctl pull request #15
Opened 2022-09-08 10:42 UTC by QuentinBisson

Towards https://github.com/giantswarm/giantswarm/issues/23238

Splitting of https://github.com/giantswarm/heartbeatctl/pull/3 part 2

2022-09-09 07:24 UTC, QuentinBisson commented
@TheoBrigitte the comment is resolved here :)

2022-09-12 12:40 UTC, TheoBrigitte requested changes

2022-09-12 12:40 UTC, TheoBrigitte commented on cmd/ping.go
> +		fmt.Printf("heartbeat \"%s\": %s\n", hbn, ping.Message)
`hbn` ?? This is the heartbeat codename right ? If yes I would prefer something like name


```suggestion
	for name, ping := range pings {
		fmt.Printf("heartbeat \"%s\": %s\n", name, ping.Message)
```

2022-09-12 12:40 UTC, TheoBrigitte commented on pkg/ctl/ports.go
> +	// heartbeats specify a `nameExpressions=['.*']` rule explicitly).
Please add a line on what is returned, especially what value is use as key in the map.

2022-09-12 12:44 UTC, QuentinBisson commented on pkg/ctl/ports.go
> +	// heartbeats specify a `nameExpressions=['.*']` rule explicitly).
@TheoBrigitte does that work ?

2022-09-14 12:16 UTC, TheoBrigitte commented on pkg/ctl/ports.go
> +	// heartbeats specify a `nameExpressions=['.*']` rule explicitly).
yes

2022-09-14 12:17 UTC, merged