Add ping and tests
giantswarm/heartbeatctl pull request #16
Opened 2022-09-08 10:48 UTC by QuentinBisson

Towards https://github.com/giantswarm/giantswarm/issues/23238

Splitting of https://github.com/giantswarm/heartbeatctl/pull/3 part 3

2022-09-08 16:33 UTC, TheoBrigitte requested changes

2022-09-08 16:33 UTC, TheoBrigitte commented on cmd/ping.go
> +		Heartbeats to ping can be specified by a combination of selectors all of
Indentation feels wrong and we can use more spaces here.

```suggestion
	        Issue a ping request to specified heartbeats.

		Beware that receiving a successful response does not necessarily mean that 
		the heartbeat exists: https://docs.opsgenie.com/docs/heartbeat-api#ping-heartbeat-request

		Heartbeats to ping can be specified by a combination of selectors all of
```

2022-09-08 16:33 UTC, TheoBrigitte commented on cmd/ping.go
> +		log.Fatalf("Failed to ping heartbeats: %v\n", err)
:+1:

2022-09-08 16:33 UTC, TheoBrigitte commented on cmd/ping.go
> +		Heartbeats to ping can be specified by a combination of selectors all of
Sorry got confuse this is actually for https://github.com/giantswarm/heartbeatctl/pull/15/

2022-09-09 08:00 UTC, QuentinBisson commented on cmd/ping.go
> +		Heartbeats to ping can be specified by a combination of selectors all of
Solved in 15

2022-09-15 14:14 UTC, QuentinBisson commented
@giantswarm/team-atlas can I get a pair of eyes?

2022-09-15 15:24 UTC, TheoBrigitte requested changes

2022-09-15 15:24 UTC, TheoBrigitte commented on pkg/ctl/adapter.go
> +			return pingResults, fmt.Errorf("heartbeat \"%s\" failed: %w", h.Name, err)
I would prefer too print what was done as soon as it happen. Like not returning anything from this function but actually printing the ping being done. Otherwise we will just be blind on what occurred when there's an error.

Another solution is to keep this as is and actually print the results and the error in the calling function, but this feels weird to me and not very Go idiomatic.

2022-09-16 12:35 UTC, QuentinBisson commented on pkg/ctl/adapter.go
> +			return pingResults, fmt.Errorf("heartbeat \"%s\" failed: %w", h.Name, err)
I'm not sure I understand why we would be blind when an error occurs as we return with an error in case one happens.

Also this repository was build using the hexagonal architecture/onion architecture which means that any side effects (logs, network requests, and so on) are not written in the adapter code. This is a pattern for clean code so I do not really agree with you that is is not go idiomatic.

We will still log in the outer function but uncorrelating this code with logging here allows us to do some extra things in the calling function and this makes this code easier to test

2022-09-16 13:57 UTC, QuentinBisson commented on pkg/ctl/adapter.go
> +			return pingResults, fmt.Errorf("heartbeat \"%s\" failed: %w", h.Name, err)
cc @TheoBrigitte :)

2022-09-23 10:02 UTC, TheoBrigitte commented on pkg/ctl/adapter.go
> +			return pingResults, fmt.Errorf("heartbeat \"%s\" failed: %w", h.Name, err)
Sorry I did not express my first thought, which is that : this function will stop whenever we encounter an error and therefore prevent pinging more heartbeats.

When issuing a ping command I would prefer that we ping as much heartbeat as possible.

2022-09-26 10:32 UTC, QuentinBisson commented on pkg/ctl/adapter.go
> +		return pingResults, fmt.Errorf("heartbeats \"%v\" failed", failedPings)
@TheoBrigitte does that addresses your comment?

2022-09-28 12:20 UTC, QuentinBisson commented
@TheoBrigitte can you take another look?

2022-09-29 15:52 UTC, TheoBrigitte commented on pkg/ctl/adapter.go
>  	if len(failedPings) > 0 {
About next line, I think the printing could be a bit better than just printing the array via `%v`.

2022-09-29 15:53 UTC, TheoBrigitte commented on pkg/ctl/adapter.go
> +		return pingResults, fmt.Errorf("heartbeats \"%v\" failed", failedPings)
I am not sure how this printing shows, but yeah this addresses my concern. Thanks

2022-09-29 15:54 UTC, TheoBrigitte approved these changes

2022-09-29 17:09 UTC, QuentinBisson commented on pkg/ctl/adapter.go
> +		return pingResults, fmt.Errorf("heartbeats \"%v\" failed", failedPings)
Thé array is printed as [cluster-id1 cluster-id2 ... Cluster-idn].
If this list is too Big, we have a Big issue

2022-09-29 17:09 UTC, merged