Add ping heartbeat command
giantswarm/heartbeatctl pull request #3
Opened 2022-08-31 09:25 UTC by QuentinBisson

Towards https://github.com/giantswarm/giantswarm/issues/23238

2022-09-06 09:06 UTC, mcbenjemaa requested changes

2022-09-06 09:06 UTC, mcbenjemaa commented on cmd/ping.go
> +	for hbn, ping := range pings {
Why you don't handle the error?

2022-09-06 09:06 UTC, mcbenjemaa commented on cmd/ping.go
> +	for hbn, ping := range pings {
Actually, I think it's better to move this logic to the underlying function `c.Ping()` 
so that, we only have one single loop.

2022-09-06 12:25 UTC, QuentinBisson commented on pkg/ctl/adapter.go
> +		// TODO: context.TODO
Done

2022-09-06 12:25 UTC, QuentinBisson commented on Dockerfile
> +ENV USER root
Fixed

2022-09-06 12:25 UTC, QuentinBisson commented on Dockerfile
> +RUN apk update
Fixed

2022-09-06 12:27 UTC, QuentinBisson commented on cmd/ping.go
> +	for hbn, ping := range pings {
The err was handled after hte loop.
I disagree with the loop management as logging to the console is a side effect of the function and I'm not sure we are really striving for that much optimization in that sample CLI :)

2022-09-08 07:39 UTC, TheoBrigitte requested changes
Overall looks good.

But I would appreciate when this PR is split into mutliple PRs:

- update the circleci config
- ping command boilerplate
- ping command implementation/logic
- refactoring/renaming

Also showing an example run would be nice.

2022-09-08 07:39 UTC, TheoBrigitte commented on .circleci/config.yml
> +          image: quay.io/giantswarm/heartbeatctl
What about other registries?

2022-09-08 07:39 UTC, TheoBrigitte commented on .nancy-ignore
> +CVE-2021-3121  until=2023-01-01
Sounds like 1.3.2 fixes this https://nvd.nist.gov/vuln/detail/cve-2021-3121
```
An issue was discovered in GoGo Protobuf before 1.3.2. plugin/unmarshal/unmarshal.go lacks certain index validation, aka the "skippy peanut butter" issue.
```

Please upgrade the dependency https://github.com/gogo/protobuf/releases/tag/v1.3.2

2022-09-08 07:39 UTC, TheoBrigitte commented on Dockerfile
> +ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Why redefining the default PATH?

```
$ docker run --rm -it alpine:3.16.2 ash -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I would suggest to remove this
```suggestion
```

2022-09-08 07:39 UTC, TheoBrigitte commented on cmd/ping.go
> +		Ping specified heartbeats to remove their expiration status.
We are not removing anything here, this feels wrong. I would prefer something like this :

```suggestion
		Issue a ping request to specified heartbeats.
```

2022-09-08 07:39 UTC, TheoBrigitte commented on cmd/ping.go
> +
Also something important from opsgenie doc and probably worth mentioning here.

`receiving a successful response does not necessarily mean that the heartbeat exists`

from: https://docs.opsgenie.com/docs/heartbeat-api#ping-heartbeat-request

2022-09-08 08:16 UTC, QuentinBisson commented on .nancy-ignore
> +CVE-2021-3121  until=2023-01-01
Oh I misread it was still in 1.3.2 and that 1.3.2 was the last version available, let's try

2022-09-08 08:22 UTC, QuentinBisson commented on Dockerfile
> +ENTRYPOINT ["/usr/local/bin/heartbeatctl"]
I did not do it on purpose :)

2022-09-08 10:42 UTC, QuentinBisson commented on cmd/ping.go
> +		Ping specified heartbeats to remove their expiration status.
Fixed in https://github.com/giantswarm/heartbeatctl/pull/15

2022-09-08 10:42 UTC, QuentinBisson commented on cmd/ping.go
> +		# ping all heartbeats with specified label 'managed-by' equal to 'foobricator'
Done in https://github.com/giantswarm/heartbeatctl/pull/15

2022-09-08 12:32 UTC, closed without merging